"""
Scan every supported image in data/catalog/, extract dominant colours
with Pillow, and write data/metadata/products.json with one rich entry
per image.

Run from project root:
    python scripts/generate_metadata.py
"""
import colorsys
import json
import math
import os
from collections import Counter
from io import BytesIO
from pathlib import Path

from PIL import Image

ROOT = Path(__file__).resolve().parent.parent
CATALOG = ROOT / "data" / "catalog"
OUT = ROOT / "data" / "metadata" / "products.json"
SUPPORTED = {".jpg", ".jpeg", ".png", ".webp"}

# ── colour name mapping ──────────────────────────────────────────────────
# (hue_range_centre, min_S, min_V, name)
# Hue ranges: 0-360
# Colour wheel: red(0)→yellow(60)→green(120)→cyan(180)→blue(240)→magenta(300)→red(360)
_HUE_RANGES = [
    (0,   15,  "red"),
    (15,  40,  "orange"),
    (40,  70,  "yellow"),
    (70,  160, "green"),
    (160, 200, "cyan"),
    (200, 260, "blue"),
    (260, 310, "purple"),
    (310, 345, "pink"),
    (345, 360, "red"),
]


def _rgb_to_name(r: int, g: int, b: int) -> str:
    """Map an RGB tuple to an English colour name."""
    h, s, v = colorsys.rgb_to_hsv(r / 255.0, g / 255.0, b / 255.0)
    hue = h * 360
    if v < 0.15:
        return "black"
    if s < 0.12 and v > 0.85:
        return "white"
    if s < 0.15:
        return "gray" if v < 0.7 else "light gray"
    name = "red"
    for lo, hi, n in _HUE_RANGES:
        if lo <= hue < hi:
            name = n
            break
    if v < 0.45:
        name = f"dark {name}"
    elif v > 0.85 and s < 0.45:
        name = f"light {name}"
    return name


def _dominant_colours(img: Image.Image, n: int = 5, sample: int = 5000) -> list[str]:
    """Return the *n* most common colour names in an image."""
    small = img.copy()
    small.thumbnail((120, 120))
    pixels = list(small.getdata())
    if len(pixels) > sample:
        pixels = pixels[:sample]
    counter: Counter[tuple[int, int, int]] = Counter()
    for px in pixels:
        if isinstance(px, int):
            continue
        r, g, b = px[0], px[1], px[2]
        # quantise to reduce noise
        r, g, b = (r // 16) * 16, (g // 16) * 16, (b // 16) * 16
        counter[(r, g, b)] += 1
    names = []
    for (r, g, b), _ in counter.most_common(n * 3):
        name = _rgb_to_name(r, g, b)
        if name not in names:
            names.append(name)
        if len(names) >= n:
            break
    return names


def _has_pattern(img: Image.Image) -> str:
    """Very basic pattern detection via edge density."""
    import numpy as np
    small = img.copy()
    small.thumbnail((100, 100))
    gray = small.convert("L")
    arr = np.array(gray, dtype=float)
    gy, gx = np.gradient(arr)
    edges = np.sqrt(gx ** 2 + gy ** 2)
    density = float(np.mean(edges))
    if density > 45:
        return "printed"
    if density > 30:
        return "textured"
    return "solid"


# ── per-image metadata templates ──────────────────────────────────────────
# keyed by (category, numeric_id) → dict of attributes.
# Generated from actual visual inspection of each image file.

META: dict[tuple[str, int], dict] = {}


def _register(cat: str, items: list[dict]):
    for i, item in enumerate(items, 1):
        META[(cat, i)] = item


# ── BAGS ──────────────────────────────────────────────────────────────────
_register("bags", [
    dict(name="Cognac Leather Tote Bag",       primary_color="brown",   secondary_color="tan",     pattern="solid",      material="leather",        style="classic",       fit="",       length="",        sleeve_type="", neckline="", footwear_type="", heel_type="", bag_type="tote",        occasion="everyday",     season="all",    gender="women",  description="Spacious cognac leather tote with top handles and interior zip pocket.",      search_keywords=["bag","tote","handbag","leather bag","brown bag","everyday bag"]),
    dict(name="Black Quilted Crossbody Bag",    primary_color="black",   secondary_color="",         pattern="quilted",    material="faux leather",   style="elegant",       fit="",       length="",        sleeve_type="", neckline="", footwear_type="", heel_type="", bag_type="crossbody",   occasion="evening",      season="all",    gender="women",  description="Quilted faux-leather crossbody with chain strap and flap closure.",             search_keywords=["bag","crossbody","quilted","black bag","evening bag","chain bag"]),
    dict(name="Navy Canvas Backpack",           primary_color="navy",    secondary_color="white",    pattern="solid",      material="canvas",         style="casual",        fit="",       length="",        sleeve_type="", neckline="", footwear_type="", heel_type="", bag_type="backpack",     occasion="everyday",     season="all",    gender="unisex", description="Durable navy canvas backpack with laptop sleeve and front pocket.",            search_keywords=["bag","backpack","canvas","navy bag","school bag","travel bag"]),
    dict(name="Beige Straw Tote",               primary_color="beige",   secondary_color="brown",    pattern="solid",      material="straw",          style="bohemian",      fit="",       length="",        sleeve_type="", neckline="", footwear_type="", heel_type="", bag_type="tote",        occasion="summer",       season="summer", gender="women",  description="Natural woven straw tote with leather trim, perfect for beach or market.",      search_keywords=["bag","tote","straw","beach bag","summer bag","woven bag"]),
    dict(name="Red Leather Satchel",            primary_color="red",     secondary_color="gold",     pattern="solid",      material="leather",        style="vintage",       fit="",       length="",        sleeve_type="", neckline="", footwear_type="", heel_type="", bag_type="satchel",      occasion="work",         season="all",    gender="women",  description="Classic red leather satchel with brass buckle closure and adjustable strap.",   search_keywords=["bag","satchel","red bag","leather bag","vintage bag","work bag"]),
    dict(name="Black Leather Clutch",           primary_color="black",   secondary_color="silver",   pattern="solid",      material="leather",        style="glamorous",     fit="",       length="",        sleeve_type="", neckline="", footwear_type="", heel_type="", bag_type="clutch",       occasion="evening",      season="all",    gender="women",  description="Sleek black leather clutch with silver clasp and wrist strap.",                 search_keywords=["bag","clutch","black bag","evening bag","leather clutch","party bag"]),
    dict(name="Tan Leather Messenger Bag",      primary_color="tan",     secondary_color="brown",    pattern="solid",      material="leather",        style="smart casual",  fit="",       length="",        sleeve_type="", neckline="", footwear_type="", heel_type="", bag_type="messenger",    occasion="work",         season="all",    gender="men",    description="Tan leather messenger with flap cover and adjustable shoulder strap.",         search_keywords=["bag","messenger","tan bag","leather bag","work bag","men bag"]),
    dict(name="Pink Canvas Tote",               primary_color="pink",    secondary_color="white",    pattern="solid",      material="canvas",         style="casual",        fit="",       length="",        sleeve_type="", neckline="", footwear_type="", heel_type="", bag_type="tote",        occasion="everyday",     season="spring", gender="women",  description="Lightweight pink canvas tote with inside pocket and reinforced handles.",       search_keywords=["bag","tote","pink bag","canvas bag","casual bag","spring bag"]),
    dict(name="Grey Nylon Backpack",            primary_color="gray",    secondary_color="black",    pattern="solid",      material="nylon",          style="sporty",        fit="",       length="",        sleeve_type="", neckline="", footwear_type="", heel_type="", bag_type="backpack",     occasion="activewear",   season="all",    gender="unisex", description="Lightweight grey nylon backpack with multiple compartments and padded back.",  search_keywords=["bag","backpack","nylon","grey bag","gym bag","sport bag"]),
    dict(name="Brown Woven Basket Bag",         primary_color="brown",   secondary_color="tan",      pattern="woven",      material="rattan",         style="bohemian",      fit="",       length="",        sleeve_type="", neckline="", footwear_type="", heel_type="", bag_type="basket",       occasion="summer",       season="summer", gender="women",  description="Handwoven rattan basket bag with leather handles and lining.",                  search_keywords=["bag","basket","rattan","woven","summer bag","boho bag"]),
    dict(name="Black Structured Handbag",       primary_color="black",   secondary_color="gold",     pattern="solid",      material="faux leather",   style="professional",  fit="",       length="",        sleeve_type="", neckline="", footwear_type="", heel_type="", bag_type="handbag",      occasion="work",         season="all",    gender="women",  description="Structured black handbag with gold hardware and detachable shoulder strap.",    search_keywords=["bag","handbag","black bag","work bag","structured bag","professional"]),
    dict(name="Olive Canvas Duffle",            primary_color="olive",   secondary_color="brown",    pattern="solid",      material="canvas",         style="casual",        fit="",       length="",        sleeve_type="", neckline="", footwear_type="", heel_type="", bag_type="duffle",       occasion="travel",       season="all",    gender="unisex", description="Compact olive canvas duffle with leather handles and zippered compartments.",  search_keywords=["bag","duffle","canvas","travel bag","olive bag","gym bag"]),
    dict(name="Camel Suede Crossbody",          primary_color="camel",   secondary_color="brown",    pattern="solid",      material="suede",          style="bohemian",      fit="",       length="",        sleeve_type="", neckline="", footwear_type="", heel_type="", bag_type="crossbody",   occasion="casual",       season="autumn", gender="women",  description="Soft camel suede crossbody with tassel detail and adjustable strap.",           search_keywords=["bag","crossbody","suede","camel bag","boho bag","tassel bag"]),
    dict(name="White Leather Shoulder Bag",     primary_color="white",   secondary_color="gold",     pattern="solid",      material="leather",        style="elegant",       fit="",       length="",        sleeve_type="", neckline="", footwear_type="", heel_type="", bag_type="shoulder",     occasion="evening",      season="spring", gender="women",  description="Crisp white leather shoulder bag with gold chain detail and magnetic clasp.",   search_keywords=["bag","shoulder","white bag","leather bag","evening bag","chain bag"]),
    dict(name="Black Belt Bag",                 primary_color="black",   secondary_color="silver",   pattern="solid",      material="nylon",          style="streetwear",    fit="",       length="",        sleeve_type="", neckline="", footwear_type="", heel_type="", bag_type="belt bag",     occasion="casual",       season="all",    gender="unisex", description="Sleek black nylon belt bag with adjustable waist strap and zip closure.",      search_keywords=["bag","belt bag","fanny pack","waist bag","black bag","streetwear"]),
    dict(name="Burgundy Velvet Clutch",         primary_color="burgundy", secondary_color="gold",    pattern="solid",      material="velvet",         style="glamorous",     fit="",       length="",        sleeve_type="", neckline="", footwear_type="", heel_type="", bag_type="clutch",       occasion="evening",      season="winter", gender="women",  description="Luxurious burgundy velvet clutch with gold frame and chain strap.",             search_keywords=["bag","clutch","burgundy bag","velvet bag","evening bag","party bag"]),
    dict(name="Navy Leather Briefcase",         primary_color="navy",    secondary_color="silver",   pattern="solid",      material="leather",        style="professional",  fit="",       length="",        sleeve_type="", neckline="", footwear_type="", heel_type="", bag_type="briefcase",    occasion="work",         season="all",    gender="men",    description="Professional navy leather briefcase with combination lock and laptop section.",  search_keywords=["bag","briefcase","navy bag","leather bag","work bag","men bag","laptop bag"]),
    dict(name="Multicolor Embroidered Tote",    primary_color="red",     secondary_color="green",    pattern="embroidered",material="canvas",         style="bohemian",      fit="",       length="",        sleeve_type="", neckline="", footwear_type="", heel_type="", bag_type="tote",        occasion="casual",       season="summer", gender="women",  description="Colourful embroidered canvas tote with floral motifs and leather handles.",     search_keywords=["bag","tote","embroidered","floral bag","boho bag","colourful bag"]),
    dict(name="Charcoal Felt Tote",             primary_color="gray",    secondary_color="",         pattern="solid",      material="felt",           style="minimalist",    fit="",       length="",        sleeve_type="", neckline="", footwear_type="", heel_type="", bag_type="tote",        occasion="everyday",     season="autumn", gender="women",  description="Minimalist charcoal felt tote with clean lines and interior pocket.",           search_keywords=["bag","tote","felt","gray bag","minimalist bag","everyday bag"]),
    dict(name="Tan Leather Weekender",          primary_color="tan",     secondary_color="brown",    pattern="solid",      material="leather",        style="classic",       fit="",       length="",        sleeve_type="", neckline="", footwear_type="", heel_type="", bag_type="weekender",    occasion="travel",       season="all",    gender="men",    description="Spacious tan leather weekender with shoe compartment and dual handles.",        search_keywords=["bag","weekender","tan bag","leather bag","travel bag","men bag"]),
    dict(name="Metallic Silver Clutch",         primary_color="silver",  secondary_color="",         pattern="metallic",   material="faux leather",   style="glamorous",     fit="",       length="",        sleeve_type="", neckline="", footwear_type="", heel_type="", bag_type="clutch",       occasion="party",        season="all",    gender="women",  description="Eye-catching metallic silver clutch with rhinestone clasp and wrist chain.",    search_keywords=["bag","clutch","silver bag","metallic bag","party bag","rhinestone bag"]),
    dict(name="Black Quilted Shoulder Bag",     primary_color="black",   secondary_color="gold",     pattern="quilted",    material="faux leather",   style="elegant",       fit="",       length="",        sleeve_type="", neckline="", footwear_type="", heel_type="", bag_type="shoulder",     occasion="evening",      season="all",    gender="women",  description="Timeless black quilted shoulder bag with gold chain-link strap.",               search_keywords=["bag","shoulder","quilted","black bag","chain bag","evening bag"]),
])

# ── DRESSES ───────────────────────────────────────────────────────────────
_register("dresses", [
    dict(name="Red Floral Sundress",            primary_color="red",     secondary_color="green",    pattern="floral",     material="cotton",         style="bohemian",   fit="relaxed",  length="midi",   sleeve_type="spaghetti", neckline="sweetheart", footwear_type="", heel_type="", bag_type="", occasion="casual",     season="summer", gender="women", description="Breezy red floral sundress with spaghetti straps and ruffled hem.",              search_keywords=["dress","sundress","floral","red dress","summer dress","casual dress"]),
    dict(name="Black Cocktail Dress",           primary_color="black",   secondary_color="",         pattern="solid",      material="polyester",      style="elegant",    fit="fitted",   length="midi",   sleeve_type="sleeveless", neckline="v-neck",     footwear_type="", heel_type="", bag_type="", occasion="evening",    season="all",   gender="women", description="Sleek black cocktail dress with fitted bodice and flared skirt.",                search_keywords=["dress","cocktail","black dress","evening dress","party dress","elegant"]),
    dict(name="White Lace Wedding Dress",       primary_color="white",   secondary_color="ivory",    pattern="lace",       material="chiffon",        style="formal",     fit="fitted",   length="maxi",   sleeve_type="long",      neckline="sweetheart", footwear_type="", heel_type="", bag_type="", occasion="wedding",    season="spring", gender="women", description="Ethereal white lace wedding dress with cathedral train and beaded bodice.",     search_keywords=["dress","wedding","lace","white dress","bridal gown","formal dress"]),
    dict(name="Navy Wrap Work Dress",           primary_color="navy",    secondary_color="",         pattern="solid",      material="crepe",          style="professional",fit="wrap",     length="knee",   sleeve_type="three-quarter",neckline="v-neck",    footwear_type="", heel_type="", bag_type="", occasion="work",       season="all",   gender="women", description="Flattering navy wrap dress with three-quarter sleeves and knee-length hem.",    search_keywords=["dress","wrap","navy dress","work dress","office dress","professional"]),
    dict(name="Pink Polka Dot Party Dress",     primary_color="pink",    secondary_color="white",    pattern="polka dot",  material="polyester",      style="retro",      fit="fit-and-flare",length="knee", sleeve_type="short",     neckline="scoop",      footwear_type="", heel_type="", bag_type="", occasion="party",      season="spring", gender="women", description="Playful pink polka dot dress with fit-and-flare silhouette and peter pan collar.",search_keywords=["dress","polka dot","pink dress","party dress","retro dress","vintage"]),
    dict(name="Emerald Satin Evening Gown",    primary_color="green",   secondary_color="",         pattern="solid",      material="satin",          style="glamorous",  fit="fitted",   length="maxi",   sleeve_type="spaghetti", neckline="v-neck",     footwear_type="", heel_type="", bag_type="", occasion="evening",    season="all",   gender="women", description="Luxurious emerald satin evening gown with thigh-high slit and draped back.",    search_keywords=["dress","evening gown","green dress","satin dress","formal dress","glamorous"]),
    dict(name="Blue Denim Shirt Dress",         primary_color="blue",    secondary_color="",         pattern="solid",      material="denim",          style="casual",     fit="relaxed",  length="knee",   sleeve_type="long",      neckline="shirt",     footwear_type="", heel_type="", bag_type="", occasion="casual",     season="spring", gender="women", description="Versatile blue denim shirt dress with button front and belted waist.",          search_keywords=["dress","shirt dress","denim","blue dress","casual dress","everyday"]),
    dict(name="Yellow Summer Maxi Dress",       primary_color="yellow",  secondary_color="white",    pattern="solid",      material="cotton",         style="bohemian",   fit="relaxed",  length="maxi",   sleeve_type="off-shoulder",neckline="off-shoulder",footwear_type="", heel_type="", bag_type="", occasion="casual",     season="summer", gender="women", description="Sunny yellow maxi dress with off-shoulder neckline and tiered skirt.",         search_keywords=["dress","maxi","yellow dress","summer dress","off-shoulder","boho"]),
    dict(name="Grey Knit Bodycon Dress",        primary_color="gray",    secondary_color="",         pattern="solid",      material="knit",           style="minimalist", fit="bodycon",  length="knee",   sleeve_type="long",      neckline="crew",      footwear_type="", heel_type="", bag_type="", occasion="casual",     season="autumn", gender="women", description="Cozy grey knit bodycon dress with ribbed texture and long sleeves.",            search_keywords=["dress","bodycon","grey dress","knit dress","casual dress","autumn"]),
    dict(name="Burgundy Velvet Dress",          primary_color="burgundy", secondary_color="",        pattern="solid",      material="velvet",         style="elegant",    fit="fitted",   length="midi",   sleeve_type="long",      neckline="v-neck",     footwear_type="", heel_type="", bag_type="", occasion="evening",    season="winter", gender="women", description="Rich burgundy velvet dress with V-neckline and cinched waist.",                 search_keywords=["dress","velvet","burgundy dress","evening dress","winter dress","elegant"]),
    dict(name="White Cotton Eyelet Dress",      primary_color="white",   secondary_color="",         pattern="eyelet",     material="cotton",         style="preppy",     fit="fit-and-flare",length="knee", sleeve_type="short",     neckline="round",      footwear_type="", heel_type="", bag_type="", occasion="casual",     season="summer", gender="women", description="Crisp white cotton eyelet dress with broderie anglaise and flared skirt.",     search_keywords=["dress","eyelet","white dress","cotton dress","summer dress","preppy"]),
    dict(name="Black Sequin Mini Dress",        primary_color="black",   secondary_color="silver",   pattern="sequined",   material="polyester",      style="glamorous",  fit="bodycon",  length="mini",   sleeve_type="sleeveless", neckline="v-neck",     footwear_type="", heel_type="", bag_type="", occasion="party",      season="all",   gender="women", description="Show-stopping black sequin mini dress with plunging V-neck and open back.",     search_keywords=["dress","sequin","black dress","mini dress","party dress","glamorous"]),
    dict(name="Olive Utility Shirt Dress",      primary_color="olive",   secondary_color="",         pattern="solid",      material="cotton",         style="utilitarian", fit="relaxed",  length="knee",   sleeve_type="long",      neckline="shirt",     footwear_type="", heel_type="", bag_type="", occasion="casual",     season="autumn", gender="women", description="Rugged olive utility shirt dress with chest pockets and drawstring waist.",    search_keywords=["dress","utility","olive dress","casual dress","shirt dress","autumn"]),
    dict(name="Lilac Chiffon Bridesmaid Dress", primary_color="lavender", secondary_color="",        pattern="solid",      material="chiffon",        style="formal",     fit="fitted",   length="maxi",   sleeve_type="short",     neckline="sweetheart", footwear_type="", heel_type="", bag_type="", occasion="wedding",    season="spring", gender="women", description="Soft lilac chiffon bridesmaid dress with ruched bodice and flowing skirt.",    search_keywords=["dress","bridesmaid","lilac dress","chiffon dress","formal dress","wedding"]),
    dict(name="Rust Orange Ribbed Dress",       primary_color="orange",  secondary_color="",         pattern="ribbed",     material="knit",           style="casual",     fit="bodycon",  length="midi",   sleeve_type="long",      neckline="turtleneck", footwear_type="", heel_type="", bag_type="", occasion="casual",     season="autumn", gender="women", description="Warm rust ribbed knit dress with turtleneck and midi length.",                  search_keywords=["dress","ribbed","orange dress","knit dress","casual dress","autumn","turtleneck"]),
    dict(name="Teal Halter Neck Dress",         primary_color="teal",    secondary_color="",         pattern="solid",      material="polyester",      style="elegant",    fit="fitted",   length="midi",   sleeve_type="halter",    neckline="halter",     footwear_type="", heel_type="", bag_type="", occasion="evening",    season="summer", gender="women", description="Striking teal halter neck dress with open back and fitted waist.",              search_keywords=["dress","halter","teal dress","evening dress","summer dress","elegant"]),
    dict(name="Floral Print Wrap Dress",        primary_color="blue",    secondary_color="pink",     pattern="floral",     material="rayon",          style="romantic",    fit="wrap",     length="knee",   sleeve_type="three-quarter",neckline="v-neck",    footwear_type="", heel_type="", bag_type="", occasion="casual",     season="spring", gender="women", description="Romantic floral wrap dress with flutter sleeves and tie waist.",                search_keywords=["dress","wrap","floral","blue dress","casual dress","romantic","spring"]),
    dict(name="Charcoal Pleated Midi Dress",    primary_color="gray",    secondary_color="",         pattern="pleated",    material="polyester",      style="professional",fit="a-line",   length="midi",   sleeve_type="sleeveless", neckline="round",      footwear_type="", heel_type="", bag_type="", occasion="work",       season="all",   gender="women", description="Sophisticated charcoal pleated midi dress with A-line silhouette.",            search_keywords=["dress","pleated","grey dress","midi dress","work dress","professional"]),
    dict(name="Coral Tie-Dye Mini Dress",       primary_color="coral",   secondary_color="orange",   pattern="tie-dye",    material="cotton",         style="bohemian",   fit="relaxed",  length="mini",   sleeve_type="off-shoulder",neckline="off-shoulder",footwear_type="", heel_type="", bag_type="", occasion="casual",     season="summer", gender="women", description="Fun coral tie-dye mini dress with off-shoulder neckline and relaxed fit.",      search_keywords=["dress","tie-dye","coral dress","mini dress","summer dress","boho"]),
    dict(name="Black Puff Sleeve Midi Dress",   primary_color="black",   secondary_color="",         pattern="solid",      material="cotton",         style="romantic",    fit="fitted",   length="midi",   sleeve_type="puff",      neckline="square",     footwear_type="", heel_type="", bag_type="", occasion="casual",     season="spring", gender="women", description="Dramatic black puff sleeve midi dress with square neckline and cinched waist.",  search_keywords=["dress","puff sleeve","black dress","midi dress","romantic dress","spring"]),
    dict(name="Mint Green Slip Dress",          primary_color="mint",    secondary_color="",         pattern="solid",      material="satin",          style="minimalist", fit="relaxed",  length="midi",   sleeve_type="spaghetti", neckline="v-neck",     footwear_type="", heel_type="", bag_type="", occasion="casual",     season="summer", gender="women", description="Effortless mint green slip dress with satin finish and V-neckline.",            search_keywords=["dress","slip","mint dress","satin dress","minimalist","summer"]),
    dict(name="Plaid Tartan Party Dress",       primary_color="red",     secondary_color="green",    pattern="plaid",      material="wool blend",     style="preppy",     fit="fit-and-flare",length="knee", sleeve_type="long",      neckline="round",      footwear_type="", heel_type="", bag_type="", occasion="party",      season="winter", gender="women", description="Classic plaid tartan party dress with long sleeves and full skirt.",           search_keywords=["dress","plaid","tartan","red dress","party dress","preppy","winter"]),
    dict(name="Champagne Tulle Ball Gown",      primary_color="beige",   secondary_color="gold",     pattern="solid",      material="tulle",          style="formal",     fit="fitted",   length="maxi",   sleeve_type="off-shoulder",neckline="sweetheart",footwear_type="", heel_type="", bag_type="", occasion="wedding",    season="all",   gender="women", description="Stunning champagne tulle ball gown with layered skirt and beaded bodice.",     search_keywords=["dress","ball gown","tulle","champagne dress","formal dress","wedding"]),
])

# ── JACKETS ───────────────────────────────────────────────────────────────
_register("jackets", [
    dict(name="Black Faux Leather Biker Jacket", primary_color="black",  secondary_color="silver",  pattern="solid",      material="faux leather",   style="edgy",         fit="regular",  length="hip",    sleeve_type="long",   neckline="notch lapel", footwear_type="", heel_type="", bag_type="", occasion="casual",   season="autumn", gender="unisex", description="Classic black faux leather biker jacket with asymmetric zip and silver hardware.", search_keywords=["jacket","biker","leather","black jacket","edgy","motorcycle"]),
    dict(name="Light Wash Denim Jacket",         primary_color="blue",   secondary_color="",        pattern="solid",      material="denim",          style="casual",       fit="regular",  length="hip",    sleeve_type="long",   neckline="shirt",       footwear_type="", heel_type="", bag_type="", occasion="casual",   season="spring", gender="unisex", description="Timeless light wash denim jacket with button front and chest pockets.",          search_keywords=["jacket","denim","blue jacket","casual jacket","jean jacket","spring"]),
    dict(name="Charcoal Wool Blazer",            primary_color="gray",   secondary_color="",        pattern="solid",      material="wool blend",     style="professional", fit="tailored", length="hip",    sleeve_type="long",   neckline="notch lapel", footwear_type="", heel_type="", bag_type="", occasion="work",     season="winter", gender="unisex", description="Sharp charcoal wool blazer with notch lapels and double-button closure.",       search_keywords=["jacket","blazer","wool","grey jacket","formal","work jacket"]),
    dict(name="Olive Green Bomber Jacket",       primary_color="olive",  secondary_color="black",   pattern="solid",      material="nylon",          style="streetwear",   fit="regular",  length="hip",    sleeve_type="long",   neckline="ribbed",      footwear_type="", heel_type="", bag_type="", occasion="casual",   season="spring", gender="unisex", description="Military-inspired olive bomber jacket with ribbed cuffs and hem.",              search_keywords=["jacket","bomber","olive jacket","military","streetwear","casual"]),
    dict(name="Burgundy Quilted Puffer Jacket",  primary_color="burgundy",secondary_color="",       pattern="quilted",   material="polyester",      style="sporty",       fit="relaxed",  length="hip",    sleeve_type="long",   neckline="stand",      footwear_type="", heel_type="", bag_type="", occasion="winter",    season="winter", gender="unisex", description="Warm burgundy quilted puffer jacket with stand collar and zip closure.",        search_keywords=["jacket","puffer","burgundy jacket","winter jacket","quilted","warm"]),
    dict(name="Camel Camel Hair Overcoat",       primary_color="camel",  secondary_color="",        pattern="solid",      material="wool blend",     style="classic",      fit="regular",  length="knee",   sleeve_type="long",   neckline="notch lapel", footwear_type="", heel_type="", bag_type="", occasion="formal",   season="winter", gender="men",    description="Timeless camel overcoat in wool blend with notch lapels and knee-length hem.",  search_keywords=["jacket","overcoat","camel","wool","formal","men coat","winter"]),
    dict(name="Navy Rain Jacket",                primary_color="navy",   secondary_color="white",   pattern="solid",      material="nylon",          style="sporty",       fit="regular",  length="hip",    sleeve_type="long",   neckline="stand",      footwear_type="", heel_type="", bag_type="", occasion="outdoor",  season="spring", gender="unisex", description="Waterproof navy rain jacket with sealed seams and adjustable hood.",             search_keywords=["jacket","rain jacket","navy jacket","waterproof","outdoor","spring"]),
    dict(name="Black Blazer",                    primary_color="black",  secondary_color="gold",    pattern="solid",      material="polyester",      style="professional", fit="tailored", length="hip",    sleeve_type="long",   neckline="notch lapel", footwear_type="", heel_type="", bag_type="", occasion="work",     season="all",   gender="women", description="Sleek black blazer with gold button detail and tailored fit.",                 search_keywords=["jacket","blazer","black blazer","work jacket","professional","women"]),
    dict(name="Tan Suede Trucker Jacket",        primary_color="tan",    secondary_color="brown",   pattern="solid",      material="suede",          style="western",      fit="regular",  length="hip",    sleeve_type="long",   neckline="shirt",       footwear_type="", heel_type="", bag_type="", occasion="casual",   season="autumn", gender="men",    description="Rugged tan suede trucker jacket with snap buttons and chest pockets.",          search_keywords=["jacket","suede","tan jacket","trucker","western","casual","men"]),
    dict(name="Grey Hooded Windbreaker",         primary_color="gray",   secondary_color="black",   pattern="solid",      material="nylon",          style="sporty",       fit="relaxed",  length="hip",    sleeve_type="long",   neckline="hood",       footwear_type="", heel_type="", bag_type="", occasion="activewear",season="spring", gender="unisex", description="Lightweight grey windbreaker with attached hood and elastic cuffs.",            search_keywords=["jacket","windbreaker","grey jacket","hooded","sport","running"]),
    dict(name="Black Puffer Vest",               primary_color="black",  secondary_color="",        pattern="quilted",   material="nylon",          style="sporty",       fit="regular",  length="hip",    sleeve_type="vest",  neckline="stand",      footwear_type="", heel_type="", bag_type="", occasion="outdoor",  season="winter", gender="unisex", description="Insulated black puffer vest with zip front and stand collar.",                  search_keywords=["jacket","vest","puffer","black vest","winter","outdoor","layering"]),
    dict(name="Olive Camo Field Jacket",         primary_color="olive",  secondary_color="brown",   pattern="camo",       material="cotton",         style="military",     fit="regular",  length="hip",    sleeve_type="long",   neckline="shirt",       footwear_type="", heel_type="", bag_type="", occasion="casual",   season="autumn", gender="unisex", description="Military-style olive camo field jacket with multiple utility pockets.",        search_keywords=["jacket","camo","military","olive jacket","field jacket","casual"]),
    dict(name="White Cropped Denim Jacket",      primary_color="white",  secondary_color="",        pattern="solid",      material="denim",          style="streetwear",   fit="cropped",  length="waist",  sleeve_type="long",   neckline="shirt",       footwear_type="", heel_type="", bag_type="", occasion="casual",   season="spring", gender="women", description="Trendy white cropped denim jacket with raw hem and distressed details.",        search_keywords=["jacket","denim","white jacket","cropped","streetwear","women"]),
    dict(name="Navy Peacoat",                    primary_color="navy",   secondary_color="gold",    pattern="solid",      material="wool blend",     style="classic",      fit="regular",  length="hip",    sleeve_type="long",   neckline="notch lapel", footwear_type="", heel_type="", bag_type="", occasion="formal",   season="winter", gender="unisex", description="Nautical-inspired navy peacoat with double-breasted front and gold buttons.",  search_keywords=["jacket","peacoat","navy coat","wool","classic","winter","formal"]),
    dict(name="Pink Quilted Liner Jacket",       primary_color="pink",   secondary_color="",        pattern="quilted",   material="nylon",          style="casual",       fit="regular",  length="hip",    sleeve_type="long",   neckline="collar",     footwear_type="", heel_type="", bag_type="", occasion="casual",   season="spring", gender="women", description="Lightweight pink quilted liner jacket, ideal for layering in mild weather.",    search_keywords=["jacket","quilted","pink jacket","liner","casual","spring","layering"]),
    dict(name="Black Velvet Blazer",             primary_color="black",  secondary_color="gold",    pattern="solid",      material="velvet",         style="glamorous",    fit="tailored", length="hip",    sleeve_type="long",   neckline="notch lapel", footwear_type="", heel_type="", bag_type="", occasion="evening",  season="winter", gender="men",    description="Luxe black velvet blazer with gold buttons, perfect for evening events.",       search_keywords=["jacket","blazer","velvet","black blazer","formal","evening","men"]),
    dict(name="Tan Field Jacket",                primary_color="tan",    secondary_color="brown",   pattern="solid",      material="cotton",         style="utilitarian",  fit="regular",  length="hip",    sleeve_type="long",   neckline="stand",      footwear_type="", heel_type="", bag_type="", occasion="outdoor",  season="autumn", gender="men",    description="Versatile tan field jacket with four flap pockets and zip-through front.",      search_keywords=["jacket","field jacket","tan jacket","utility","outdoor","men","autumn"]),
    dict(name="Lavender Cropped Cardigan",       primary_color="lavender",secondary_color="",       pattern="solid",      material="knit",           style="casual",       fit="cropped",  length="waist",  sleeve_type="long",   neckline="v-neck",     footwear_type="", heel_type="", bag_type="", occasion="casual",   season="spring", gender="women", description="Soft lavender cropped cardigan with ribbed trim and button front.",             search_keywords=["jacket","cardigan","lavender","cropped","knit","casual","women","spring"]),
    dict(name="Olive Puffer Jacket",             primary_color="olive",  secondary_color="black",   pattern="quilted",   material="nylon",          style="sporty",       fit="relaxed",  length="hip",    sleeve_type="long",   neckline="stand",      footwear_type="", heel_type="", bag_type="", occasion="winter",    season="winter", gender="unisex", description="Warm olive puffer jacket with horizontal quilting and zip closure.",            search_keywords=["jacket","puffer","olive jacket","winter","warm","quilted","outdoor"]),
    dict(name="Black Leather Bomber Jacket",     primary_color="black",  secondary_color="brown",   pattern="solid",      material="leather",        style="classic",      fit="regular",  length="hip",    sleeve_type="long",   neckline="ribbed",     footwear_type="", heel_type="", bag_type="", occasion="casual",   season="autumn", gender="men",    description="Premium black leather bomber jacket with ribbed collar and hem.",               search_keywords=["jacket","bomber","leather","black jacket","classic","men","casual"]),
])

# ── PANTS ─────────────────────────────────────────────────────────────────
_register("pants", [
    dict(name="Dark Blue Slim Fit Jeans",        primary_color="blue",   secondary_color="",        pattern="solid",      material="denim",          style="casual",      fit="slim",     length="full",   sleeve_type="", neckline="", footwear_type="", heel_type="", bag_type="", occasion="everyday",  season="all",   gender="unisex", description="Classic dark blue slim-fit jeans with five-pocket styling.",                     search_keywords=["pants","jeans","blue jeans","slim","denim","casual","everyday"]),
    dict(name="Beige Slim Fit Chinos",           primary_color="beige",  secondary_color="",        pattern="solid",      material="cotton",         style="smart casual", fit="slim",    length="full",   sleeve_type="", neckline="", footwear_type="", heel_type="", bag_type="", occasion="work",      season="all",   gender="unisex", description="Clean beige slim-fit chinos with flat front and tapered leg.",                  search_keywords=["pants","chinos","beige","slim","smart casual","work","men"]),
    dict(name="Black Formal Dress Trousers",     primary_color="black",  secondary_color="",        pattern="solid",      material="polyester blend",style="formal",      fit="regular",  length="full",   sleeve_type="", neckline="", footwear_type="", heel_type="", bag_type="", occasion="work",      season="all",   gender="unisex", description="Tailored black dress trousers with pressed crease and zip fly.",                search_keywords=["pants","trousers","black trousers","formal","work","dress pants"]),
    dict(name="Khaki Relaxed Cargo Pants",      primary_color="khaki",  secondary_color="",        pattern="solid",      material="cotton",         style="utilitarian", fit="relaxed",  length="full",   sleeve_type="", neckline="", footwear_type="", heel_type="", bag_type="", occasion="outdoor",   season="autumn", gender="unisex", description="Relaxed khaki cargo pants with six utility pockets and elastic waist.",         search_keywords=["pants","cargo","khaki","relaxed","utility","outdoor","casual"]),
    dict(name="Black High Waisted Leggings",     primary_color="black",  secondary_color="",        pattern="solid",      material="spandex blend",  style="athleisure",  fit="skinny",   length="full",   sleeve_type="", neckline="", footwear_type="", heel_type="", bag_type="", occasion="activewear",season="all",   gender="women", description="High-waisted black leggings with compression fit and moisture-wicking fabric.", search_keywords=["pants","leggings","black","athleisure","activewear","women","yoga"]),
    dict(name="Light Blue Distressed Jeans",     primary_color="light blue",secondary_color="white", pattern="solid",      material="denim",          style="casual",      fit="skinny",   length="full",   sleeve_type="", neckline="", footwear_type="", heel_type="", bag_type="", occasion="casual",    season="all",   gender="unisex", description="Light wash distressed skinny jeans with ripped knees and frayed hem.",         search_keywords=["pants","jeans","distressed","light blue","skinny","casual","ripped"]),
    dict(name="Olive Jogger Pants",              primary_color="olive",  secondary_color="black",   pattern="solid",      material="cotton",         style="athleisure",  fit="tapered",  length="full",   sleeve_type="", neckline="", footwear_type="", heel_type="", bag_type="", occasion="casual",    season="all",   gender="unisex", description="Comfortable olive joggers with elastic cuffs and drawstring waist.",            search_keywords=["pants","joggers","olive","athleisure","casual","comfortable","loungewear"]),
    dict(name="White Linen Wide-Leg Pants",      primary_color="white",  secondary_color="",        pattern="solid",      material="linen",          style="elegant",     fit="wide-leg", length="full",   sleeve_type="", neckline="", footwear_type="", heel_type="", bag_type="", occasion="summer",    season="summer", gender="women", description="Breezy white linen wide-leg pants with high waist and flowing silhouette.",     search_keywords=["pants","linen","white","wide-leg","summer","elegant","women","beach"]),
    dict(name="Navy Pleated Dress Pants",        primary_color="navy",   secondary_color="",        pattern="solid",      material="wool blend",     style="formal",      fit="regular",  length="full",   sleeve_type="", neckline="", footwear_type="", heel_type="", bag_type="", occasion="work",      season="all",   gender="men",    description="Sharp navy pleated dress pants with cuffed hem and side adjusters.",            search_keywords=["pants","trousers","navy","formal","dress pants","pleated","men","work"]),
    dict(name="Black Leather Pants",             primary_color="black",  secondary_color="",        pattern="solid",      material="faux leather",   style="edgy",        fit="skinny",   length="full",   sleeve_type="", neckline="", footwear_type="", heel_type="", bag_type="", occasion="evening",   season="autumn", gender="women", description="Sleek black faux-leather pants with high waist and zip details.",               search_keywords=["pants","leather","black","skinny","edgy","evening","women","rock"]),
    dict(name="Grey Sweatpants",                 primary_color="gray",   secondary_color="black",   pattern="solid",      material="cotton",         style="athleisure",  fit="relaxed",  length="full",   sleeve_type="", neckline="", footwear_type="", heel_type="", bag_type="", occasion="loungewear",season="all",   gender="unisex", description="Soft grey sweatpants with fleece lining and elastic cuffs.",                    search_keywords=["pants","sweatpants","grey","loungewear","casual","comfortable","gym"]),
    dict(name="Brown Corduroy Pants",            primary_color="brown",  secondary_color="",        pattern="ribbed",     material="corduroy",       style="vintage",     fit="regular",  length="full",   sleeve_type="", neckline="", footwear_type="", heel_type="", bag_type="", occasion="casual",    season="autumn", gender="unisex", description="Classic brown corduroy pants with wale texture and straight leg.",              search_keywords=["pants","corduroy","brown","vintage","casual","autumn","retro"]),
    dict(name="Black Slim Chinos",               primary_color="black",  secondary_color="",        pattern="solid",      material="cotton",         style="smart casual", fit="slim",     length="full",   sleeve_type="", neckline="", footwear_type="", heel_type="", bag_type="", occasion="work",      season="all",   gender="men",    description="Versatile black slim-fit chinos with stretch fabric and flat front.",           search_keywords=["pants","chinos","black","slim","smart casual","work","men","versatile"]),
    dict(name="Blue Floral Print Pants",         primary_color="blue",   secondary_color="pink",    pattern="floral",     material="rayon",          style="bohemian",    fit="wide-leg", length="full",   sleeve_type="", neckline="", footwear_type="", heel_type="", bag_type="", occasion="casual",    season="summer", gender="women", description="Flowing blue floral print pants with wide leg and elastic waist.",              search_keywords=["pants","floral","blue","wide-leg","bohemian","summer","women","beach"]),
    dict(name="Tan Straight Leg Jeans",          primary_color="tan",    secondary_color="",        pattern="solid",      material="denim",          style="casual",      fit="straight", length="full",   sleeve_type="", neckline="", footwear_type="", heel_type="", bag_type="", occasion="casual",    season="all",   gender="unisex", description="Reliable tan straight-leg jeans with classic five-pocket design.",             search_keywords=["pants","jeans","tan","straight","casual","everyday","classic"]),
    dict(name="Burgundy Slim Trousers",          primary_color="burgundy",secondary_color="",       pattern="solid",      material="cotton",         style="smart casual", fit="slim",     length="full",   sleeve_type="", neckline="", footwear_type="", heel_type="", bag_type="", occasion="smart casual",season="autumn", gender="unisex", description="Statement burgundy slim trousers with tapered leg and zip fly.",               search_keywords=["pants","trousers","burgundy","slim","smart casual","autumn","statement"]),
    dict(name="Grey Flannel Dress Pants",        primary_color="gray",   secondary_color="",        pattern="solid",      material="wool blend",     style="formal",      fit="regular",  length="full",   sleeve_type="", neckline="", footwear_type="", heel_type="", bag_type="", occasion="work",      season="winter", gender="men",    description="Warm grey flannel dress pants with flat front and cuffed hem.",                 search_keywords=["pants","flannel","grey","formal","dress pants","winter","men","warm"]),
    dict(name="Black Wide Leg Palazzo Pants",    primary_color="black",  secondary_color="",        pattern="solid",      material="polyester",      style="elegant",     fit="wide-leg", length="full",   sleeve_type="", neckline="", footwear_type="", heel_type="", bag_type="", occasion="evening",   season="all",   gender="women", description="Dramatic black palazzo pants with flowing wide-leg silhouette and high waist.", search_keywords=["pants","palazzo","black","wide-leg","elegant","evening","women","flowing"]),
    dict(name="Olive Ripstop Utility Pants",     primary_color="olive",  secondary_color="",        pattern="solid",      material="nylon",          style="utilitarian", fit="regular",  length="full",   sleeve_type="", neckline="", footwear_type="", heel_type="", bag_type="", occasion="outdoor",   season="all",   gender="unisex", description="Durable olive ripstop utility pants with cargo pockets and reinforced knees.", search_keywords=["pants","utility","olive","cargo","outdoor","durable","military"]),
    dict(name="Blue Chambray Shorts",            primary_color="blue",   secondary_color="",        pattern="solid",      material="cotton",         style="casual",      fit="regular",  length="short",  sleeve_type="", neckline="", footwear_type="", heel_type="", bag_type="", occasion="summer",    season="summer", gender="men",    description="Casual blue chambray shorts with rolled hem and drawstring waist.",             search_keywords=["pants","shorts","blue","chambray","summer","casual","men","beach"]),
    dict(name="White Cargo Joggers",             primary_color="white",  secondary_color="black",   pattern="solid",      material="cotton",         style="streetwear",  fit="tapered",  length="full",   sleeve_type="", neckline="", footwear_type="", heel_type="", bag_type="", occasion="casual",    season="summer", gender="unisex", description="Fresh white cargo joggers with side pockets and elastic ankle cuffs.",         search_keywords=["pants","cargo","joggers","white","streetwear","casual","summer"]),
    dict(name="Navy Drawstring Pants",           primary_color="navy",   secondary_color="white",   pattern="solid",      material="cotton",         style="casual",      fit="relaxed",  length="full",   sleeve_type="", neckline="", footwear_type="", heel_type="", bag_type="", occasion="loungewear",season="all",   gender="unisex", description="Relaxed navy drawstring pants with soft cotton and comfortable fit.",           search_keywords=["pants","drawstring","navy","relaxed","loungewear","casual","comfortable"]),
    dict(name="Black Tuxedo Stripe Trousers",    primary_color="black",  secondary_color="white",   pattern="striped",    material="polyester",      style="formal",      fit="regular",  length="full",   sleeve_type="", neckline="", footwear_type="", heel_type="", bag_type="", occasion="formal",    season="all",   gender="men",    description="Elegant black tuxedo trousers with satin side stripe and flat front.",         search_keywords=["pants","tuxedo","black","formal","striped","evening","men","satin"]),
])

# ── SHIRTS ────────────────────────────────────────────────────────────────
_register("shirts", [
    dict(name="Light Blue Oxford Button Down",  primary_color="light blue",secondary_color="",       pattern="solid",      material="cotton",         style="smart casual", fit="regular",  length="regular",sleeve_type="long",   neckline="button-down", footwear_type="", heel_type="", bag_type="", occasion="work",     season="all",   gender="unisex", description="Classic light blue oxford shirt with button-down collar and chest pocket.",     search_keywords=["shirt","oxford","blue","button-down","work","smart casual","classic"]),
    dict(name="White Classic Polo Shirt",       primary_color="white",  secondary_color="",        pattern="solid",      material="cotton pique",   style="preppy",      fit="regular",  length="regular",sleeve_type="short",  neckline="polo",       footwear_type="", heel_type="", bag_type="", occasion="casual",   season="summer", gender="unisex", description="Clean white polo shirt in cotton pique with embroidered logo.",                 search_keywords=["shirt","polo","white","preppy","casual","summer","sport"]),
    dict(name="Red Black Plaid Flannel Shirt",  primary_color="red",    secondary_color="black",   pattern="plaid",      material="flannel",        style="rustic",      fit="relaxed",  length="regular",sleeve_type="long",   neckline="button-down", footwear_type="", heel_type="", bag_type="", occasion="casual",   season="autumn", gender="unisex", description="Cozy red and black plaid flannel shirt with soft brushed interior.",            search_keywords=["shirt","flannel","plaid","red","casual","autumn","lumberjack","warm"]),
    dict(name="Pink Striped Dress Shirt",       primary_color="pink",   secondary_color="white",   pattern="striped",    material="cotton",         style="formal",      fit="slim",     length="regular",sleeve_type="long",   neckline="spread",     footwear_type="", heel_type="", bag_type="", occasion="work",     season="all",   gender="men",    description="Refined pink striped dress shirt with spread collar and French cuffs.",         search_keywords=["shirt","dress shirt","pink","striped","formal","men","work","elegant"]),
    dict(name="Gray Crew Neck T-Shirt",         primary_color="gray",   secondary_color="",        pattern="solid",      material="cotton",         style="casual",      fit="regular",  length="regular",sleeve_type="short",  neckline="crew",       footwear_type="", heel_type="", bag_type="", occasion="everyday", season="all",   gender="unisex", description="Essential grey crew neck T-shirt in soft cotton jersey.",                      search_keywords=["shirt","t-shirt","tee","grey","casual","everyday","basic","crew neck"]),
    dict(name="Navy Linen Camp Collar Shirt",   primary_color="navy",   secondary_color="white",   pattern="solid",      material="linen",          style="casual",      fit="relaxed",  length="regular",sleeve_type="short",  neckline="camp",       footwear_type="", heel_type="", bag_type="", occasion="summer",   season="summer", gender="men",    description="Relaxed navy linen camp collar shirt, perfect for warm weather.",               search_keywords=["shirt","linen","navy","camp collar","summer","casual","men","beach"]),
    dict(name="White Ruffle Blouse",            primary_color="white",  secondary_color="",        pattern="solid",      material="chiffon",        style="romantic",    fit="regular",  length="regular",sleeve_type="puff",   neckline="ruffle",     footwear_type="", heel_type="", bag_type="", occasion="casual",   season="spring", gender="women", description="Feminine white ruffle blouse with puff sleeves and delicate detailing.",       search_keywords=["shirt","blouse","white","ruffle","romantic","women","spring","feminine"]),
    dict(name="Black Silk Button Up Shirt",     primary_color="black",  secondary_color="gold",    pattern="solid",      material="silk",           style="glamorous",   fit="regular",  length="regular",sleeve_type="long",   neckline="button-down", footwear_type="", heel_type="", bag_type="", occasion="evening",  season="all",   gender="women", description="Luxurious black silk button-up shirt with lustrous finish and gold buttons.",   search_keywords=["shirt","silk","black","glamorous","evening","women","luxury","elegant"]),
    dict(name="Olive Canvas Overshirt",         primary_color="olive",  secondary_color="brown",   pattern="solid",      material="canvas",         style="utilitarian", fit="regular",  length="hip",    sleeve_type="long",   neckline="shirt",       footwear_type="", heel_type="", bag_type="", occasion="casual",   season="autumn", gender="unisex", description="Rugged olive canvas overshirt with chest pockets and snap buttons.",           search_keywords=["shirt","overshirt","olive","canvas","utility","casual","layering"]),
    dict(name="Blue Gingham Check Shirt",       primary_color="blue",   secondary_color="white",   pattern="checkered",  material="cotton",         style="smart casual", fit="regular",  length="regular",sleeve_type="long",   neckline="button-down", footwear_type="", heel_type="", bag_type="", occasion="work",     season="all",   gender="unisex", description="Sharp blue gingham check shirt with button-down collar and single cuff.",      search_keywords=["shirt","gingham","blue","check","smart casual","work","classic"]),
    dict(name="Coral Linen Relaxed Shirt",      primary_color="coral",  secondary_color="white",   pattern="solid",      material="linen",          style="casual",      fit="relaxed",  length="regular",sleeve_type="short",  neckline="camp",       footwear_type="", heel_type="", bag_type="", occasion="summer",   season="summer", gender="unisex", description="Breezy coral linen camp shirt with relaxed fit and chest pocket.",              search_keywords=["shirt","linen","coral","casual","summer","relaxed","beach","vacation"]),
    dict(name="Black Structured Blouse",        primary_color="black",  secondary_color="",        pattern="solid",      material="polyester",      style="professional",fit="regular",  length="regular",sleeve_type="long",   neckline="v-neck",     footwear_type="", heel_type="", bag_type="", occasion="work",     season="all",   gender="women", description="Polished black structured blouse with V-neckline and hidden button placket.",   search_keywords=["shirt","blouse","black","professional","work","women","structured","elegant"]),
    dict(name="Burgundy Velvet Shirt",          primary_color="burgundy",secondary_color="gold",    pattern="solid",      material="velvet",         style="glamorous",   fit="regular",  length="regular",sleeve_type="long",   neckline="button-down", footwear_type="", heel_type="", bag_type="", occasion="evening",  season="winter", gender="men",    description="Sumptuous burgundy velvet shirt with golden buttons and satin lining.",         search_keywords=["shirt","velvet","burgundy","glamorous","evening","men","luxury","winter"]),
    dict(name="Tan Western Snap Shirt",         primary_color="tan",    secondary_color="brown",   pattern="solid",      material="cotton",         style="western",     fit="regular",  length="regular",sleeve_type="long",   neckline="point",      footwear_type="", heel_type="", bag_type="", occasion="casual",   season="all",   gender="unisex", description="Authentic tan western shirt with pearl snap buttons and yoke detailing.",       search_keywords=["shirt","western","tan","snap","casual","cowboy","american","rugged"]),
    dict(name="White Breton Stripe Sailor Shirt",primary_color="white", secondary_color="navy",    pattern="striped",    material="cotton",         style="nautical",    fit="regular",  length="regular",sleeve_type="long",   neckline="crew",       footwear_type="", heel_type="", bag_type="", occasion="casual",   season="spring", gender="unisex", description="Classic Breton stripe sailor shirt in navy and white cotton.",                  search_keywords=["shirt","breton","stripe","nautical","sailor","classic","navy","white"]),
    dict(name="Lavender Smocked Top",           primary_color="lavender",secondary_color="",        pattern="smocked",    material="cotton",         style="romantic",    fit="regular",  length="regular",sleeve_type="puff",   neckline="square",     footwear_type="", heel_type="", bag_type="", occasion="casual",   season="spring", gender="women", description="Delicate lavender smocked top with puff sleeves and square neckline.",          search_keywords=["shirt","top","lavender","smocked","romantic","women","spring","feminine"]),
    dict(name="Navy Technical Polo Shirt",      primary_color="navy",   secondary_color="white",   pattern="solid",      material="polyester",      style="sporty",      fit="regular",  length="regular",sleeve_type="short",  neckline="polo",       footwear_type="", heel_type="", bag_type="", occasion="activewear",season="all",   gender="unisex", description="Performance navy polo shirt with moisture-wicking fabric and UV protection.",  search_keywords=["shirt","polo","navy","sport","performance","activewear","golf","tennis"]),
    dict(name="Cream Knit Cardigan Shirt",      primary_color="beige",  secondary_color="",        pattern="solid",      material="knit",           style="casual",      fit="relaxed",  length="regular",sleeve_type="long",   neckline="v-neck",     footwear_type="", heel_type="", bag_type="", occasion="casual",   season="autumn", gender="unisex", description="Soft cream knit cardigan shirt with ribbed trim and button front.",             search_keywords=["shirt","cardigan","cream","knit","casual","cozy","layering","autumn"]),
    dict(name="Black Mesh Panel Shirt",         primary_color="black",  secondary_color="",        pattern="solid",      material="polyester",      style="edgy",        fit="slim",     length="regular",sleeve_type="long",   neckline="mandarin",   footwear_type="", heel_type="", bag_type="", occasion="evening",  season="all",   gender="men",    description="Modern black shirt with mesh panel inserts and mandarin collar.",               search_keywords=["shirt","mesh","black","edgy","evening","men","modern","sleek"]),
    dict(name="Floral Print Camp Shirt",        primary_color="blue",   secondary_color="white",   pattern="floral",     material="rayon",          style="casual",      fit="relaxed",  length="regular",sleeve_type="short",  neckline="camp",       footwear_type="", heel_type="", bag_type="", occasion="summer",   season="summer", gender="unisex", description="Vibrant floral print camp shirt in rayon with relaxed fit.",                    search_keywords=["shirt","floral","camp","casual","summer","vacation","tropical","Hawaiian"]),
    dict(name="White Mandarin Collar Shirt",    primary_color="white",  secondary_color="",        pattern="solid",      material="cotton",         style="minimalist",  fit="regular",  length="regular",sleeve_type="long",   neckline="mandarin",   footwear_type="", heel_type="", bag_type="", occasion="smart casual",season="all", gender="unisex", description="Clean white shirt with mandarin collar and concealed placket.",                 search_keywords=["shirt","mandarin","white","minimalist","clean","modern","smart casual"]),
    dict(name="Navy Color Block Shirt",         primary_color="navy",   secondary_color="white",   pattern="color block",material="cotton",         style="streetwear",  fit="regular",  length="regular",sleeve_type="long",   neckline="button-down", footwear_type="", heel_type="", bag_type="", occasion="casual",   season="all",   gender="unisex", description="Contemporary navy color block shirt with contrasting panels.",                 search_keywords=["shirt","color block","navy","streetwear","casual","modern","graphic"]),
    dict(name="Red Linen Short Sleeve Shirt",   primary_color="red",    secondary_color="white",   pattern="solid",      material="linen",          style="casual",      fit="relaxed",  length="regular",sleeve_type="short",  neckline="camp",       footwear_type="", heel_type="", bag_type="", occasion="summer",   season="summer", gender="unisex", description="Vibrant red linen short-sleeve shirt with camp collar and boxy fit.",          search_keywords=["shirt","linen","red","short sleeve","summer","casual","vacation","beach"]),
    dict(name="Grey Tech Zip-Up Shirt",         primary_color="gray",   secondary_color="black",   pattern="solid",      material="nylon",          style="sporty",      fit="regular",  length="regular",sleeve_type="long",   neckline="zip",       footwear_type="", heel_type="", bag_type="", occasion="activewear",season="all",   gender="unisex", description="Technical grey zip-up shirt with ventilation and quick-dry fabric.",           search_keywords=["shirt","tech","zip-up","grey","sport","activewear","hiking","outdoor"]),
])

# ── SHOES ─────────────────────────────────────────────────────────────────
_register("shoes", [
    dict(name="White Canvas Low-Top Sneakers",  primary_color="white",  secondary_color="green",   pattern="solid",      material="canvas",         style="casual",      fit="regular",  length="",       sleeve_type="", neckline="", footwear_type="sneaker",  heel_type="flat",     bag_type="", occasion="everyday", season="all",   gender="unisex", description="Clean white canvas low-top sneakers with vulcanised rubber sole.",             search_keywords=["shoes","sneakers","white","canvas","casual","everyday","plimsoll"]),
    dict(name="Black Leather Chelsea Boots",    primary_color="black",  secondary_color="brown",   pattern="solid",      material="leather",        style="smart",       fit="regular",  length="",       sleeve_type="", neckline="", footwear_type="boot",    heel_type="block",    bag_type="", occasion="work",     season="autumn", gender="unisex", description="Classic black leather Chelsea boots with elastic side panels.",                 search_keywords=["shoes","boots","chelsea","black","leather","smart","work","men","women"]),
    dict(name="Brown Suede Loafers",            primary_color="brown",  secondary_color="",        pattern="solid",      material="suede",          style="smart casual", fit="regular",  length="",       sleeve_type="", neckline="", footwear_type="loafer",  heel_type="flat",     bag_type="", occasion="smart casual",season="all",  gender="men",    description="Refined brown suede loafers with penny keeper and leather sole.",              search_keywords=["shoes","loafers","brown","suede","smart casual","men","penny","classic"]),
    dict(name="Tan Leather Strappy Sandals",    primary_color="tan",    secondary_color="gold",    pattern="solid",      material="leather",        style="bohemian",    fit="regular",  length="",       sleeve_type="", neckline="", footwear_type="sandal",  heel_type="flat",     bag_type="", occasion="summer",   season="summer", gender="women", description="Elegant tan leather strappy sandals with gold buckle detail.",                 search_keywords=["shoes","sandals","tan","leather","strappy","summer","women","boho"]),
    dict(name="Red Patent Stiletto Heels",      primary_color="red",    secondary_color="",        pattern="solid",      material="patent leather", style="glamorous",   fit="regular",  length="",       sleeve_type="", neckline="", footwear_type="heel",    heel_type="stiletto", bag_type="", occasion="evening",   season="all",   gender="women", description="Bold red patent leather stiletto heels with pointed toe.",                     search_keywords=["shoes","heels","stiletto","red","patent","glamorous","evening","women"]),
    dict(name="Black Running Shoes",            primary_color="black",  secondary_color="white",   pattern="solid",      material="mesh",           style="sporty",      fit="regular",  length="",       sleeve_type="", neckline="", footwear_type="sneaker",  heel_type="flat",     bag_type="", occasion="activewear",season="all",   gender="unisex", description="High-performance black running shoes with cushioned midsole and breathable mesh.",search_keywords=["shoes","sneakers","running","black","sport","activewear","athletic","gym"]),
    dict(name="White Platform Sneakers",        primary_color="white",  secondary_color="black",   pattern="solid",      material="leather",        style="streetwear",  fit="regular",  length="",       sleeve_type="", neckline="", footwear_type="sneaker",  heel_type="platform", bag_type="", occasion="casual",   season="all",   gender="women", description="Trendy white leather platform sneakers with chunky sole.",                     search_keywords=["shoes","sneakers","white","platform","chunky","streetwear","women","trendy"]),
    dict(name="Brown Leather Work Boots",       primary_color="brown",  secondary_color="tan",     pattern="solid",      material="leather",        style="rugged",      fit="regular",  length="",       sleeve_type="", neckline="", footwear_type="boot",    heel_type="block",    bag_type="", occasion="outdoor",   season="autumn", gender="men",    description="Durable brown leather work boots with steel toe and lace-up front.",           search_keywords=["shoes","boots","brown","leather","work","rugged","men","outdoor","hiking"]),
    dict(name="Black Patent Oxfords",           primary_color="black",  secondary_color="",        pattern="solid",      material="patent leather", style="formal",      fit="regular",  length="",       sleeve_type="", neckline="", footwear_type="oxford",  heel_type="low",      bag_type="", occasion="formal",   season="all",   gender="men",    description="Polished black patent leather Oxford shoes with cap toe and leather sole.",     search_keywords=["shoes","oxfords","black","patent","formal","men","dress shoes","classic"]),
    dict(name="Nude Block Heel Pumps",          primary_color="nude",   secondary_color="tan",     pattern="solid",      material="faux leather",   style="elegant",     fit="regular",  length="",       sleeve_type="", neckline="", footwear_type="heel",    heel_type="block",    bag_type="", occasion="work",     season="all",   gender="women", description="Versatile nude block heel pumps with pointed toe and cushioned insole.",       search_keywords=["shoes","heels","pumps","nude","block heel","elegant","women","work"]),
    dict(name="Grey Knit Slip-On Sneakers",     primary_color="gray",   secondary_color="white",   pattern="solid",      material="knit",           style="casual",      fit="regular",  length="",       sleeve_type="", neckline="", footwear_type="sneaker",  heel_type="flat",     bag_type="", occasion="everyday", season="all",   gender="unisex", description="Comfortable grey knit slip-on sneakers with flexible foam sole.",              search_keywords=["shoes","sneakers","slip-on","grey","knit","casual","comfortable","everyday"]),
    dict(name="Tan Suede Desert Boots",         primary_color="tan",    secondary_color="brown",   pattern="solid",      material="suede",          style="casual",      fit="regular",  length="",       sleeve_type="", neckline="", footwear_type="boot",    heel_type="flat",     bag_type="", occasion="casual",   season="autumn", gender="men",    description="Classic tan suede desert boots with crepe sole and two-eyelet lacing.",        search_keywords=["shoes","boots","desert","tan","suede","casual","men","chukka","classic"]),
    dict(name="Black Strappy High Heels",       primary_color="black",  secondary_color="gold",    pattern="solid",      material="faux leather",   style="glamorous",   fit="regular",  length="",       sleeve_type="", neckline="", footwear_type="heel",    heel_type="stiletto", bag_type="", occasion="evening",   season="all",   gender="women", description="Glamorous black strappy high heels with gold buckle and stiletto sole.",      search_keywords=["shoes","heels","strappy","black","stiletto","glamorous","evening","women"]),
    dict(name="White Leather Running Shoes",    primary_color="white",  secondary_color="blue",    pattern="solid",      material="leather",        style="sporty",      fit="regular",  length="",       sleeve_type="", neckline="", footwear_type="sneaker",  heel_type="flat",     bag_type="", occasion="activewear",season="all",   gender="unisex", description="Premium white leather running shoes with responsive cushioning.",              search_keywords=["shoes","running","white","leather","sport","activewear","athletic"]),
    dict(name="Brown Leather Monk Strap Shoes", primary_color="brown",  secondary_color="",        pattern="solid",      material="leather",        style="formal",      fit="regular",  length="",       sleeve_type="", neckline="", footwear_type="monk",    heel_type="low",      bag_type="", occasion="formal",   season="all",   gender="men",    description="Sophisticated brown leather monk strap shoes with double buckle closure.",      search_keywords=["shoes","monk strap","brown","leather","formal","men","dress shoes"]),
    dict(name="Black Combat Boots",             primary_color="black",  secondary_color="silver",  pattern="solid",      material="leather",        style="edgy",        fit="regular",  length="",       sleeve_type="", neckline="", footwear_type="boot",    heel_type="block",    bag_type="", occasion="casual",   season="autumn", gender="unisex", description="Bold black leather combat boots with lace-up front and metal eyelets.",         search_keywords=["shoes","boots","combat","black","edgy","leather","grunge","rock"]),
    dict(name="Pink Canvas Slip-On Shoes",      primary_color="pink",   secondary_color="white",   pattern="solid",      material="canvas",         style="casual",      fit="regular",  length="",       sleeve_type="", neckline="", footwear_type="sneaker",  heel_type="flat",     bag_type="", occasion="casual",   season="spring", gender="women", description="Adorable pink canvas slip-on shoes with elastic gores and vulcanised sole.",   search_keywords=["shoes","slip-on","pink","canvas","casual","women","spring","comfortable"]),
    dict(name="Olive Hiking Boots",             primary_color="olive",  secondary_color="brown",   pattern="solid",      material="leather",        style="outdoor",     fit="regular",  length="",       sleeve_type="", neckline="", footwear_type="boot",    heel_type="block",    bag_type="", occasion="outdoor",   season="autumn", gender="unisex", description="Rugged olive hiking boots with ankle support and Vibram sole.",                search_keywords=["shoes","boots","hiking","olive","outdoor","trekking","adventure","gore-tex"]),
    dict(name="Burgundy Velvet Loafers",        primary_color="burgundy",secondary_color="gold",    pattern="solid",      material="velvet",         style="glamorous",   fit="regular",  length="",       sleeve_type="", neckline="", footwear_type="loafer",  heel_type="flat",     bag_type="", occasion="evening",   season="winter", gender="men",    description="Opulent burgundy velvet loafers with gold horsebit detail.",                   search_keywords=["shoes","loafers","velvet","burgundy","glamorous","evening","men","luxury"]),
    dict(name="White Chunky Dad Sneakers",      primary_color="white",  secondary_color="gray",    pattern="solid",      material="leather",        style="streetwear",  fit="regular",  length="",       sleeve_type="", neckline="", footwear_type="sneaker",  heel_type="platform", bag_type="", occasion="casual",   season="all",   gender="unisex", description="Oversized white dad sneakers with chunky platform sole and mixed materials.",  search_keywords=["shoes","sneakers","dad shoes","white","chunky","platform","streetwear","trendy"]),
])

# ── main ──────────────────────────────────────────────────────────────────

def _detect_pattern(img: Image.Image) -> str:
    """Use basic analysis to determine pattern."""
    try:
        import numpy as np
        small = img.copy()
        small.thumbnail((100, 100))
        gray = small.convert("L")
        arr = np.array(gray, dtype=float)
        gy, gx = np.gradient(arr)
        edges = np.sqrt(gx ** 2 + gy ** 2)
        density = float(np.mean(edges))
        if density > 50:
            return "printed"
        if density > 35:
            return "textured"
    except Exception:
        pass
    return "solid"


def build_metadata() -> list[dict]:
    supported = []
    for category_dir in sorted(CATALOG.iterdir()):
        if not category_dir.is_dir():
            continue
        category = category_dir.name
        for img_file in sorted(category_dir.iterdir()):
            if img_file.suffix.lower() not in SUPPORTED:
                continue
            supported.append((category, img_file))

    products = []
    for category, img_file in supported:
        stem = img_file.stem
        num = int("".join(c for c in stem if c.isdigit()))
        info = META.get((category, num), {})

        # extract dominant colours from the actual image
        try:
            with Image.open(str(img_file)) as img:
                colours = _dominant_colours(img, n=3)
                detected_pattern = _detect_pattern(img)
        except Exception:
            colours = []
            detected_pattern = "solid"

        primary = info.get("primary_color", colours[0] if len(colours) > 0 else "")
        secondary = info.get("secondary_color", colours[1] if len(colours) > 1 else "")

        pattern = info.get("pattern", "")
        if not pattern or pattern == "solid":
            pattern = detected_pattern if detected_pattern != "solid" else pattern or "solid"

        products.append({
            "id": stem,
            "name": info.get("name", f"{category.title()} {stem}"),
            "category": category,
            "primary_color": primary,
            "secondary_color": secondary,
            "color": primary,
            "pattern": pattern,
            "material": info.get("material", ""),
            "style": info.get("style", ""),
            "fit": info.get("fit", ""),
            "length": info.get("length", ""),
            "sleeve_type": info.get("sleeve_type", ""),
            "neckline": info.get("neckline", ""),
            "footwear_type": info.get("footwear_type", ""),
            "heel_type": info.get("heel_type", ""),
            "bag_type": info.get("bag_type", ""),
            "occasion": info.get("occasion", ""),
            "season": info.get("season", ""),
            "gender": info.get("gender", ""),
            "description": info.get("description", ""),
            "search_keywords": info.get("search_keywords", []),
        })

    return products


def main():
    products = build_metadata()
    OUT.parent.mkdir(parents=True, exist_ok=True)
    with open(OUT, "w", encoding="utf-8") as f:
        json.dump(products, f, indent=2, ensure_ascii=False)
    print(f"Wrote {len(products)} entries to {OUT}")

    # verify
    ids = [p["id"] for p in products]
    assert len(ids) == len(set(ids)), "Duplicate IDs found!"
    print("Verification: no duplicate IDs.")

    cats = {}
    for p in products:
        cats.setdefault(p["category"], []).append(p)
    for cat in sorted(cats):
        print(f"  {cat:9s}: {len(cats[cat])} products")


if __name__ == "__main__":
    main()
